// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrcjxzktczmcnvcyuush.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyY2p4emt0Y3ptY252Y3l1dXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDk0MjYsImV4cCI6MjA2MjE4NTQyNn0.6C56Dj2e6SUchx4EZHGy8Q2_5j6gAggdVjWKCvSz2go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);